### ISSUE TITLE
Melhorias

### ISSUE THREAD

**Issue by fsantanna-uerj** [rodrigodc07/EDL#1]
- comparação entre Protocolos vs Interfaces de Java
- origens dos tipos opcionais, alguma outra linguagem oferece esse suporte? como? (ex. Haskell)

**Comment by fsantanna-uerj** [comment]
- Desenvolver a Seção de Classificação, está sem nenhum justificativa.

**Comment by fsantanna-uerj** [comment]
Vocês somaram 14 pontos, favor escolher como dividir. O máximo é 8.

**Comment by rodrigodc07** [comment]
Já desenvolvemos a seção de classificação, vamos dividir 7 para cada um

**Comment by fsantanna-uerj** [comment]
obrigado
